# Generated by Django 3.1.7 on 2021-03-17 16:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SwappRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('offered_product_owner_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('requested_product_owner_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('state', models.CharField(choices=[('IN', 'Initial'), ('AC', 'Accepted'), ('RJ', 'Rejected')], default='IN', max_length=2)),
                ('offered_product_id', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='offered_product_id', to='swapp.item')),
                ('requested_product_id', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='requested_product_id', to='swapp.item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swapp.user'),
        ),
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('donated_at', models.DateTimeField()),
                ('donor_id', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='swapp.user')),
                ('item_id', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='swapp.item')),
            ],
        ),
    ]
