# Generated by Django 3.1.7 on 2021-03-18 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swapp', '0003_auto_20210317_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='swapprequest',
            name='offered_product',
        ),
        migrations.RemoveField(
            model_name='swapprequest',
            name='requested_product',
        ),
        migrations.DeleteModel(
            name='Donations',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='SwappRequest',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
