# Generated by Django 3.1.7 on 2021-03-26 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('swapp', '0005_donation_item_profile_swapprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='donated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='out_for_request',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='picture',
            field=models.FileField(default='', upload_to='pictures'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donor',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='donation',
            name='item',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='swapp.item'),
        ),
        migrations.AlterField(
            model_name='swapprequest',
            name='offered_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offered_product_id', to='swapp.item'),
        ),
        migrations.AlterField(
            model_name='swapprequest',
            name='offered_product_owner_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='swapprequest',
            name='requested_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_product_id', to='swapp.item'),
        ),
        migrations.AlterField(
            model_name='swapprequest',
            name='requested_product_owner_id',
            field=models.BigIntegerField(),
        ),
    ]
