# Generated by Django 3.1.7 on 2021-03-26 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swapp', '0006_auto_20210326_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='swapprequest',
            name='trace_id',
            field=models.CharField(default='', max_length=30),
        ),
    ]
