# Generated by Django 3.1.7 on 2021-03-27 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swapp', '0008_swapprequest_closed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='current_location',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='item',
            name='preferred_change',
            field=models.CharField(default='', max_length=15),
        ),
    ]
