# Generated by Django 3.1.7 on 2021-03-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swapp', '0011_auto_20210328_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='removed',
            field=models.BooleanField(default=False),
        ),
    ]
